### PR TITLE
README.rst: depreciated => deprecated

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by SethMMorton** [comment]
Hmm... according to Google's dictionary, deprecate and depreciate are synonyms.  Is there a strong grammatical reason you are suggesting deprecate over depreciate?

**Comment by msabramo** [comment]
I feel like "deprecate" is much more commonly used in our industry in this context.

See http://stackoverflow.com/questions/9208091/the-difference-between-deprecated-depreciated-and-obsolete

But it's up to you. You can keep it if you like it and I won't be offended at all.

**Comment by SethMMorton** [comment]
Makes sense. It's a good suggestion, and I think there are a few more locations in my code I need to modify.

**Comment by SethMMorton** [comment]
I changed all the depreciated => deprecated in the entire codebase.

**Pull request closed without merging**
