### PR TITLE
DOC: Changed "sequence" to "iterable"

### PR DESCRIPTION
**Pull request by madphysicist**
Seemed like a good idea since I had to try it out before deciding that the docs were not precise.

### CODE REVIEW

**Comment by madphysicist** [comment]
Should have probably done `[ci skip]` since this is a doc change.

**Comment by SethMMorton** [comment]
Thanks. Sounds like a valid change. When `natsort` was young it didn't work on iterates, and it looks like I never updated that docstring.

**Comment by madphysicist** [comment]
I figured. The use case I had in mind was `natsort.natsorted(somedict.keys())`. `keys()` works fine with almost everything in Py2, crashes some stuff in Py3. Good to know `natsorted` does fine with arbitrary iterables.

**Comment by madphysicist** [comment]
So just out of curiosity, will you accept this PR?

**Comment by SethMMorton** [comment]
Yes, I merged it locally. I just haven't gotten around to pushing my changes to GitHub yet.

**Comment by madphysicist** [comment]
Take your time. I was just going through my open PRs and pinging all the ones that have been out for a while.

**Comment by SethMMorton** [comment]
I am closing now since I have pulled in the develop branch.

**Comment by madphysicist** [comment]
The doc changes are not in the `master` branch.

**Comment by SethMMorton** [comment]
I am aware. It does not make the fact that they are already merged with develop any less true. When develop is merged with master then the changes will be in master.

**Comment by madphysicist** [comment]
My mistake. I misunderstood your note to mean that develop was merged into master.

**Comment by SethMMorton** [comment]
No problem. I am getting close to merging develop into master... Maybe a day or less. Then we'll see the changes.

**Pull request closed without merging**
