### PR TITLE
Add support for Python 3.8

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
One test is failing on Python 3.8:

```
=================================== FAILURES ===================================
__ test_numeric_chars_contains_all_valid_unicode_numeric_and_digit_characters __
tests/test_unicode_numbers.py:49: in test_numeric_chars_contains_all_valid_unicode_numeric_and_digit_characters
    assert i in set_numeric_hex
E   assert 73664 in {178, 179, 185, 188, 189, 190, ...}
```

**Comment by SethMMorton** [comment]
I'm surprised that TravisCI supports Python 3.8 already... typically it takes them months to roll out support.

**Comment by SethMMorton** [comment]
Regarding the failing check, this is pretty expected. Each new Python version adds more Unicode support, and `natsort` ends up having to update its hard-coded list of valid unicode numbers. You can generate the complete list of numbers by executing `python38 natsort/unicode_numeric_hex.py` and then replace the existing list at the top of the file with the list that is output, then run `black` on the file to get it formatted.

**Comment by hugovk** [comment]
Travis was the first (of the CIs I've been checking) to add 3.8, in less than 24 hours!

It took GitHub Actions 21 days, Azure Pipelines 25 days and AppVeyor 26 days.

Thanks, will update the Unicode list when I'm next at a keyboard.

**Comment by hugovk** [comment]
Updated!

Python 3.8 passes.

`WITH_EXTRAS="fast,icu"` is now failing, but it is also now fails on master:

* https://travis-ci.org/hugovk/natsort/builds/610766292

**Comment by SethMMorton** [comment]
Huh... from the message it looks like PyICU is not building. I'll take a look.

**Comment by SethMMorton** [comment]
Looks like PyICU made an update to 2.4 yesterday and compilation started breaking across all platforms. I filed this issue as well (https://github.com/ovalhub/pyicu/issues/116), as our signature seems different from others.

**Comment by SethMMorton** [comment]
I'm going to merge this, because the failure is not related to your change.

**Comment by dvzrv** [comment]
@SethMMorton can you release a new version with this change included? We're currently already in the middle of rebuilds for python3.8 on Arch Linux and I'd like to be able to drop the patch.
Thanks! :)

**Comment by SethMMorton** [comment]
@dvzrv Hmm... I was hoping to wait and release along with the drop of 2.7 support. Though, I suppose now is as good of a time as any to start the `long-term-support` branch...

**Comment by SethMMorton** [comment]
@dvzrv What's your timeline for wanting a release with this?

**Comment by hugovk** [comment]
@SethMMorton On some projects, I have Travis CI set up to auto-deploy to PyPI on tags, it makes releasing much easier. (It also auto-deploys to Test PyPI for merges to master.)

* https://github.com/hugovk/pypistats/blob/a320ae9ceeb403242a79e65990c00725be1e5b1c/.travis.yml

* https://github.com/hugovk/pypistats/blob/a320ae9ceeb403242a79e65990c00725be1e5b1c/RELEASING.md

Let me know if you'd like something similar. I'd be happy to create a PR and help you set it up. It uses encrypted API tokens for upload: https://pypi.org/help/#apitoken.

**Comment by dvzrv** [comment]
On 2019-11-12 16:20:52 (-0800), Seth Morton wrote:
> @dvzrv What's your timeline for wanting a release with this?

asap (but no stress) ;-)

The rebuilt packages for python3.8 are already in testing, but the
previous release (and also 6.1.0) require patching to be compatible with
python3.8.

As the sources from pypi don't include certain files (e.g. .travis.yml),
that have been changed in the pull request, fixing this issue, the patch
doesn't apply cleanly.

**Comment by SethMMorton** [comment]
@dvzrv  I'll release today

**Comment by SethMMorton** [comment]
@hugovk Thank you for the suggestion. I actually had that set up many years ago but removed it because something went wrong (I don't remember what now). I would feel more comfortable if there were some sort of button I had to press in the CI to actually enact the deployment, because I am always afraid of accidentally releasing something broken.

**Comment by SethMMorton** [comment]
@dvzrv Released

**Comment by SethMMorton** [comment]
@hugovk I'm not opposed to the idea. I'd be interested in seeing the PR.

**Comment by hugovk** [comment]
Please see PR #106.

**Comment by dvzrv** [comment]
On 2019-11-13 11:44:31 (-0800), Seth Morton wrote:
> @dvzrv Released

Thank you! Works for me! :)

**Pull request merged**
