### PR TITLE
Python 2.6 compatibility

### PR DESCRIPTION
**Pull request by dpetzold**
Hello,

This pull requests adds support for Python 2.6 and Tox. I thought this would be a simple exercise but since hypothesis does not support 2.6:

 http://www.drmaciver.com/2015/05/if-you-want-python-2-6-support-pay-me/

getting the tests required a bit more effort than I was anticipating :). Since hypothesis uses decorators the tests couldn't just be skipped the decorators also had to be mocked out.  I also ran into a issue where the de_DE locale wasn't available on all versions so those are also skipped sometimes. 

The motivation for this was to get these pull requests to pass:

https://github.com/timothycrosley/isort/pulls

Just let me know if you have any questions or comments.

Thanks!,

### CODE REVIEW

**Comment by SethMMorton** [comment]
This is great! Had stopped testing against Python 2.6 because of hypothesis because it looked like too much work to make it compatible... I'm pretty impressed.  I will take a deeper look and make a new release in a hopefully a few days.

**Comment by dpetzold** [comment]
Ha yeah I was thinking it would be a small change. The actual commit for py26 compatibility was:

https://github.com/dpetzold/natsort/commit/4d04924fbb6dd8b64fcdb17eda2159d28ded2452

but then I didn't see the point of that without tox. It was a good experience and I was very happy to to be able to contribute to natsort :).

**Comment by dpetzold** [comment]
I rewrote history on this commit: 

https://github.com/dpetzold/natsort/commit/9dadb3acf2f91a84620f3a821098cd19621f5f55

To use sys.version_info. I think the tests just need to be rerun again for it to pass.

**Comment by SethMMorton** [comment]
I really like the idea of the compat folder. Most of my files probably belong in there, so I think I will make that change before release.  However, I will move the py26.py file that you added to the "test_natsort" folder, since this file will introduce a dependency on hypothesis and mock for all users even if they are not testing, which I do not want to do.

**Comment by SethMMorton** [comment]
This pull request was merged into the develop branch in commit fcda77ac5c7ea79dbdecacdca38e873c2898beda.

**Comment by dpetzold** [comment]
Hey Seth,

I was just going to followup on your feedback but I see you have already updated. Your changes look really great. Thanks for letting me contribute!

**Pull request merged**
